-- =========================================================
-- DATABASE SI PENANGKAR HORTI
-- Jalankan seluruh script ini di Supabase > SQL Editor.
-- =========================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  role text not null default 'viewer' check (role in ('viewer','editor')),
  created_at timestamptz not null default now()
);

create table if not exists public.penangkar (
  id bigint generated by default as identity primary key,
  nama text not null,
  kecamatan text not null,
  komoditas text not null,
  jenis text default '',
  alamat text default '',
  telepon text default '',
  luas numeric(10,2) default 0,
  produksi numeric(10,2) default 0,
  status text not null default 'Aktif' check (status in ('Aktif','Nonaktif')),
  verifikasi text not null default 'Belum Diverifikasi' check (verifikasi in ('Terverifikasi','Dalam Proses','Belum Diverifikasi')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1)), 'viewer')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'editor'
  );
$$;

alter table public.profiles enable row level security;
alter table public.penangkar enable row level security;

-- Profiles: pengguna hanya dapat melihat profilnya sendiri.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (id = auth.uid());

-- Penangkar: data boleh dilihat publik, tetapi hanya editor yang boleh mengubah.
drop policy if exists "penangkar_select_public" on public.penangkar;
create policy "penangkar_select_public"
on public.penangkar for select
to anon, authenticated
using (true);

drop policy if exists "penangkar_insert_editor" on public.penangkar;
create policy "penangkar_insert_editor"
on public.penangkar for insert
to authenticated
with check (public.is_editor());

drop policy if exists "penangkar_update_editor" on public.penangkar;
create policy "penangkar_update_editor"
on public.penangkar for update
to authenticated
using (public.is_editor())
with check (public.is_editor());

drop policy if exists "penangkar_delete_editor" on public.penangkar;
create policy "penangkar_delete_editor"
on public.penangkar for delete
to authenticated
using (public.is_editor());

-- Aktifkan Realtime untuk tabel penangkar.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'penangkar'
  ) then
    alter publication supabase_realtime add table public.penangkar;
  end if;
end $$;

-- =========================================================
-- SETELAH MEMBUAT USER DI AUTH:
-- 1. Buka Authentication > Users.
-- 2. Buat akun petugas dengan email + password.
-- 3. Salin UUID user tersebut.
-- 4. Jalankan:
--    update public.profiles set role='editor' where id='UUID_USER_DI_SINI';
-- =========================================================
